# DialogueManager.gd - Global manager for narrative data
# Loads JSON dialogue generated by Claude and serves it to NPCs

extends Node

var dialogue_data: Dictionary = {}
const DATA_PATH = "res://data/dialogue_db.json"

func _ready():
	load_dialogue()

func load_dialogue():
	if not FileAccess.file_exists(DATA_PATH):
		push_warning("DialogueManager: No dialogue DB found at " + DATA_PATH)
		return

	var file = FileAccess.open(DATA_PATH, FileAccess.READ)
	var json_text = file.get_as_text()
	var json = JSON.new()
	var error = json.parse(json_text)
	
	if error == OK:
		dialogue_data = json.data
		print("DialogueManager: Loaded narrative data successfully.")
	else:
		push_error("DialogueManager: JSON Parse Error: " + json.get_error_message())

# NLP Suggestive Frames (Presuppositions and Implied Inevitability)
const SUGGESTIVE_FRAMES = {
	"acceptance": ["It is natural that you [LINE].", "As you accept the records, you [LINE]."],
	"doubt": ["You might think you remember, but as you [LINE]...", "The document contradicts your thought that you [LINE]."],
	"inevitability": ["The system has already prepared the way for you to [LINE].", "Calibration is complete once you [LINE]."]
}

func get_line(npc_id: String, tier: int, category: String) -> String:
	var tier_key = "tier_" + str(tier)
	var final_text = "..."
	
	if dialogue_data.has(npc_id):
		var npc_lines = dialogue_data[npc_id]
		# Fallback to lower tiers if current tier doesn't have the key
		for t in range(tier, -1, -1):
			var t_key = "tier_" + str(t)
			if npc_lines.has(t_key) and npc_lines[t_key].has(category):
				final_text = npc_lines[t_key][category]
				break
	
	return final_text

# Wraps a line in NLP suggestive language
func apply_nlp_frame(text: String, frame_type: String = "acceptance") -> String:
	if not SUGGESTIVE_FRAMES.has(frame_type):
		return text
		
	var templates = SUGGESTIVE_FRAMES[frame_type]
	var template = templates[randi() % templates.size()]
	return template.replace("[LINE]", text.trim_suffix("."))
